In [1]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, cross_val_score #We'll also use the cross_val_score function to evaluate our model across the k folds

#For demonstration purposes, we'll use the Iris dataset and a simple classifier (LogisticRegression).



In [2]:
#Load the dataset:
data = load_iris()
X, y = data.data, data.target

In [15]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
# Set up k-fold cross-validation:
#We'll use 5-fold cross-validation in this example.
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)

#n_splits=k specifies the number of folds.
#shuffle=True ensures that the data is shuffled before splitting into folds.
#random_state=42 is an arbitrary seed for reproducibility.

In [4]:
#Apply k-fold cross-validation using a classifier:
#We'll use the cross_val_score function to evaluate the performance of our LogisticRegression classifier across the k folds.

clf = LogisticRegression(max_iter=200, random_state=42)
##max_iter=200: This specifies the maximum number of iterations the solver (i.e., the algorithm used to find the logistic regression coefficients) will take to converge. The default value is 100, but sometimes, increasing this number can help in cases where the solver might not converge quickly.


#Performing Cross-Validation:
scores = cross_val_score(clf, X, y, cv=kf)
#cv=kf: This specifies the cross-validation splitting strategy to be used. In our case, we're using the kf object we created earlier, which is a 5-fold cross-validation strategy with shuffling.


#scores will contain the accuracy of the classifier for each of the k folds.


In [5]:
scores

array([1.        , 1.        , 0.93333333, 0.96666667, 0.96666667])

In [6]:
#Analyze the results:
#We can compute the average and standard deviation of the scores to get an idea of the model's performance and variability across the folds.
average_accuracy = scores.mean()
std_accuracy = scores.std()


In [9]:

#Approximately 97.33%
average_accuracy


0.9733333333333334

In [8]:
#Standard Deviation of Accuracy: Approximately 2.49%
std_accuracy

0.024944382578492935

In [ ]:
#Note
#1. Cross validation do fit the model and discard- the purpose of this not to train model and use for prediction - the purpose of this to find accuray of diffenre - new date
#2.If you want to train model and use for prediction then you need to fit again and do prediction

In [10]:
#Supose if you want to train model for prediction
clf.fit(X, y)

LogisticRegression(max_iter=200, random_state=42)

In [12]:
#Now, you can use this trained model (clf) to make predictions on new data. Let's say you have some random data new_data:
new_data = [[5.0, 3.5, 1.5, 0.2]]
predicted_class = clf.predict(new_data)


array([0])

In [14]:
predicted_class_value = predicted_class[0]
predicted_class_value
#0 means setosa

0

In [ ]:
#The purpose of cross-validation is not to train a final model for deployment
#but rather to assess how well the model is expected to perform on unseen data.

In [17]:
#Install flask ngrok, to expose this enviroment publicly
!pip install flask-ngrok


In [23]:
!pip install flask-ngrok

from flask import Flask, request, jsonify
from flask_ngrok import run_with_ngrok
import numpy as np

app = Flask(__name__)
run_with_ngrok(app)  # Start ngrok when the app is run

# Load pre-trained model (for simplicity, we'll use the model trained earlier in this conversation)
model = clf

@app.route('/predict', methods=['POST'])
def predict():

    # Mapping of class labels to flower names
    class_names = {0: "setosa", 1: "versicolor", 2: "virginica"}

    data = request.json
    prediction = model.predict(np.array([data['input']])) #We extract the input data from the received JSON (using data['input']), convert it to a numpy array, and then use the pre-trained model to make a prediction.
    flower_name = class_names[int(prediction[0])]

    return jsonify({'prediction': int(prediction[0]), 'flower_name': flower_name})

if __name__ == '__main__':
    app.run()


 * Serving Flask app '__main__'
 * Debug mode: off


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit


 * Running on http://1cf1-35-186-170-27.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040


INFO:werkzeug:127.0.0.1 - - [21/Oct/2023 18:30:06] "POST /predict HTTP/1.1" 200 -
